export const languages = [
  // { label: "Auto-detect", value: "auto" },
  { label: "TypeScript", value: "tsx" },
  { label: "JavaScript", value: "js" },
  { label: "JSON", value: "json" },
  { label: "CSS", value: "css" },
  { label: "HTML", value: "html" },
  { label: "XML", value: "xml" },
  { label: "Markdown", value: "md" },
  { label: "YAML", value: "yaml" },
  { label: "Rust", value: "rs" },
  { label: "Python", value: "py" },
  { label: "Go", value: "go" },
  { label: "Java", value: "java" },
  { label: "C++", value: "cpp" },
  { label: "C#", value: "cs" },
  { label: "PHP", value: "php" },
  { label: "Plain Text", value: "txt" },
  { label: "Ruby", value: "rb" },
] as const


export const darkthemes = [
  "pierre-dark",
  "andromeeda",
  "aurora-x",
  "ayu-dark",
  "catppuccin-frappe",
  "catppuccin-macchiato",
  "catppuccin-mocha",
  "dark-plus",
  "dracula",
  "dracula-soft",
  "everforest-dark",
  "github-dark",
  "github-dark-default",
  "github-dark-dimmed",
  "github-dark-high-contrast",
  "gruvbox-dark-hard",
  "gruvbox-dark-medium",
  "gruvbox-dark-soft",
  "houston",
  "kanagawa-dragon",
  "kanagawa-wave",
  "laserwave",
  "material-theme",
  "material-theme-darker",
  "material-theme-ocean",
  "material-theme-palenight",
  "min-dark",
  "monokai",
  "night-owl",
  "nord",
  "one-dark-pro",
  "plastic",
  "poimandres",
  "red",
  "rose-pine",
  "rose-pine-moon",
  "slack-dark",
  "solarized-dark",
  "synthwave-84",
  "tokyo-night",
  "vesper",
  "vitesse-black",
  "vitesse-dark"
] as const

export const lightthemes = [
  "pierre-light",
  "catppuccin-latte",
  "everforest-light",
  "github-light",
  "github-light-default",
  "github-light-high-contrast",
  "gruvbox-light-hard",
  "gruvbox-light-medium",
  "gruvbox-light-soft",
  "kanagawa-lotus",
  "light-plus",
  "material-theme-lighter",
  "min-light",
  "one-light",
  "rose-pine-dawn",
  "slack-ochin",
  "snazzy-light",
  "solarized-light",
  "vitesse-light"
] as const

export type CodeThemes = typeof darkthemes[number] | typeof lightthemes[number]