import type { Metadata, Viewport } from "next"
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "next-themes"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
})

const jetbrains_mono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: [ "latin" ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  colorScheme: "light dark"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${ geistSans.variable } ${ geistMono.variable } ${ jetbrains_mono.variable } h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <ThemeScript />
      </head>
      {/* <ThemeProvider> */}
      <body className="min-h-full flex flex-col">
        {children}
      </body>
      {/* </ThemeProvider> */}
    </html>
  )
}


// Scripts -----------------------------

function ThemeScript() {
  return (
    <script id="theme">{`const theme = localStorage.getItem('theme');
if (theme === null || !['light', 'dark', 'system'].includes(theme)) {
  localStorage.setItem('theme', 'system');
  document.documentElement.style.colorScheme = 'light dark';
} else {
  if (theme === 'system') {
    document.documentElement.style.colorScheme = 'light dark';
  } else {
    document.documentElement.style.colorScheme = theme;
  }
}`}</script>
  )
}